export const CATEGORIES_DATA = [
    { "idx": 0, "id": 1, "pregunta_id": "Q_1", "nombre_categoria": "Bienestar subjetivo" },
    { "idx": 1, "id": 2, "pregunta_id": "Q_2", "nombre_categoria": "Bienestar subjetivo" },
    { "idx": 2, "id": 3, "pregunta_id": "Q_3", "nombre_categoria": "Bienestar subjetivo" },
    { "idx": 3, "id": 4, "pregunta_id": "Q_4", "nombre_categoria": "Bienestar subjetivo" },
    { "idx": 4, "id": 5, "pregunta_id": "Q_5", "nombre_categoria": "Bienestar subjetivo" },
    { "idx": 5, "id": 6, "pregunta_id": "Q_6", "nombre_categoria": "Relaciones interpersonales" },
    { "idx": 6, "id": 7, "pregunta_id": "Q_7", "nombre_categoria": "Relaciones interpersonales" },
    { "idx": 7, "id": 8, "pregunta_id": "Q_8", "nombre_categoria": "Relaciones interpersonales" },
    { "idx": 8, "id": 9, "pregunta_id": "Q_9", "nombre_categoria": "Relaciones interpersonales" },
    { "idx": 9, "id": 10, "pregunta_id": "Q_10", "nombre_categoria": "Relaciones interpersonales" },
    { "idx": 10, "id": 11, "pregunta_id": "Q_11", "nombre_categoria": "Relaciones interpersonales" },
    { "idx": 11, "id": 12, "pregunta_id": "T_Q_12_1", "nombre_categoria": "Relaciones interpersonales" },
    { "idx": 12, "id": 13, "pregunta_id": "T_Q_12_2", "nombre_categoria": "Relaciones interpersonales" },
    { "idx": 13, "id": 14, "pregunta_id": "T_Q_12_3", "nombre_categoria": "Relaciones interpersonales" },
    { "idx": 14, "id": 15, "pregunta_id": "T_Q_12_4", "nombre_categoria": "Relaciones interpersonales" },
    { "idx": 15, "id": 16, "pregunta_id": "T_Q_12_5", "nombre_categoria": "Relaciones interpersonales" },
    { "idx": 16, "id": 17, "pregunta_id": "T_Q_13_1", "nombre_categoria": "Relaciones interpersonales" },
    { "idx": 17, "id": 18, "pregunta_id": "T_Q_13_2", "nombre_categoria": "Relaciones interpersonales" },
    { "idx": 18, "id": 19, "pregunta_id": "T_Q_13_3", "nombre_categoria": "Relaciones interpersonales" },
    { "idx": 19, "id": 20, "pregunta_id": "T_Q_13_4", "nombre_categoria": "Relaciones interpersonales" },
    { "idx": 20, "id": 21, "pregunta_id": "T_Q_13_5", "nombre_categoria": "Relaciones interpersonales" },
    { "idx": 21, "id": 22, "pregunta_id": "T_Q_13_6", "nombre_categoria": "Relaciones interpersonales" },
    { "idx": 22, "id": 23, "pregunta_id": "Q_21", "nombre_categoria": "Economía" },
    { "idx": 23, "id": 24, "pregunta_id": "Q_20", "nombre_categoria": "Economía" },
    { "idx": 24, "id": 25, "pregunta_id": "Q_19", "nombre_categoria": "Economía" },
    { "idx": 25, "id": 26, "pregunta_id": "Q_18", "nombre_categoria": "Economía" },
    { "idx": 26, "id": 27, "pregunta_id": "Q_17", "nombre_categoria": "Economía" },
    { "idx": 27, "id": 28, "pregunta_id": "Q_16", "nombre_categoria": "Economía" },
    { "idx": 28, "id": 29, "pregunta_id": "Q_15", "nombre_categoria": "Economía" },
    { "idx": 29, "id": 30, "pregunta_id": "Q_14", "nombre_categoria": "Economía" },
    { "idx": 30, "id": 39, "pregunta_id": "Q_22", "nombre_categoria": "Salud" },
    { "idx": 31, "id": 40, "pregunta_id": "Q_23_O1", "nombre_categoria": "Salud" },
    { "idx": 32, "id": 41, "pregunta_id": "Q_23_O2", "nombre_categoria": "Salud" },
    { "idx": 33, "id": 42, "pregunta_id": "Q_23_O3", "nombre_categoria": "Salud" },
    { "idx": 34, "id": 43, "pregunta_id": "Q_23_O4", "nombre_categoria": "Salud" },
    { "idx": 35, "id": 44, "pregunta_id": "Q_23_O5", "nombre_categoria": "Salud" },
    { "idx": 36, "id": 45, "pregunta_id": "Q_24", "nombre_categoria": "Salud" },
    { "idx": 37, "id": 46, "pregunta_id": "T_Q_25_1", "nombre_categoria": "Salud" },
    { "idx": 38, "id": 47, "pregunta_id": "T_Q_25_2", "nombre_categoria": "Salud" },
    { "idx": 39, "id": 48, "pregunta_id": "T_Q_25_3", "nombre_categoria": "Salud" },
    { "idx": 40, "id": 49, "pregunta_id": "T_Q_25_4", "nombre_categoria": "Salud" },
    { "idx": 41, "id": 50, "pregunta_id": "T_Q_25_5", "nombre_categoria": "Salud" },
    { "idx": 42, "id": 51, "pregunta_id": "T_Q_25_6", "nombre_categoria": "Salud" },
    { "idx": 43, "id": 52, "pregunta_id": "T_Q_26_1", "nombre_categoria": "Salud" },
    { "idx": 44, "id": 53, "pregunta_id": "T_Q_26_2", "nombre_categoria": "Salud" },
    { "idx": 45, "id": 54, "pregunta_id": "T_Q_26_3", "nombre_categoria": "Salud" },
    { "idx": 46, "id": 55, "pregunta_id": "T_Q_26_4", "nombre_categoria": "Salud" },
    { "idx": 47, "id": 56, "pregunta_id": "T_Q_26_5", "nombre_categoria": "Salud" },
    { "idx": 48, "id": 57, "pregunta_id": "T_Q_26_6", "nombre_categoria": "Salud" },
    { "idx": 49, "id": 58, "pregunta_id": "T_Q_27_1", "nombre_categoria": "Salud" },
    { "idx": 50, "id": 59, "pregunta_id": "T_Q_27_2", "nombre_categoria": "Salud" },
    { "idx": 51, "id": 60, "pregunta_id": "T_Q_27_3", "nombre_categoria": "Salud" },
    { "idx": 52, "id": 61, "pregunta_id": "T_Q_27_4", "nombre_categoria": "Salud" },
    { "idx": 53, "id": 62, "pregunta_id": "T_Q_27_5", "nombre_categoria": "Salud" },
    { "idx": 54, "id": 63, "pregunta_id": "T_Q_27_6", "nombre_categoria": "Salud" },
    { "idx": 55, "id": 64, "pregunta_id": "T_Q_28_1", "nombre_categoria": "Salud" },
    { "idx": 56, "id": 65, "pregunta_id": "T_Q_28_2", "nombre_categoria": "Salud" },
    { "idx": 57, "id": 66, "pregunta_id": "T_Q_28_3", "nombre_categoria": "Salud" },
    { "idx": 58, "id": 67, "pregunta_id": "T_Q_28_4", "nombre_categoria": "Salud" },
    { "idx": 59, "id": 68, "pregunta_id": "T_Q_28_5", "nombre_categoria": "Salud" },
    { "idx": 60, "id": 69, "pregunta_id": "T_Q_28_6", "nombre_categoria": "Salud" },
    { "idx": 61, "id": 70, "pregunta_id": "T_Q_28_7", "nombre_categoria": "Salud" },
    { "idx": 62, "id": 71, "pregunta_id": "T_Q_28_8", "nombre_categoria": "Salud" },
    { "idx": 63, "id": 72, "pregunta_id": "T_Q_28_9", "nombre_categoria": "Salud" },
    { "idx": 64, "id": 73, "pregunta_id": "T_Q_29_1", "nombre_categoria": "Salud" },
    { "idx": 65, "id": 74, "pregunta_id": "T_Q_29_2", "nombre_categoria": "Salud" },
    { "idx": 66, "id": 75, "pregunta_id": "T_Q_30_1", "nombre_categoria": "Salud" },
    { "idx": 67, "id": 76, "pregunta_id": "T_Q_30_2", "nombre_categoria": "Salud" },
    { "idx": 68, "id": 77, "pregunta_id": "T_Q_30_3", "nombre_categoria": "Salud" },
    { "idx": 69, "id": 78, "pregunta_id": "T_Q_30_4", "nombre_categoria": "Salud" },
    { "idx": 70, "id": 79, "pregunta_id": "T_Q_30_5", "nombre_categoria": "Salud" },
    { "idx": 71, "id": 80, "pregunta_id": "T_Q_30_6", "nombre_categoria": "Salud" },
    { "idx": 72, "id": 81, "pregunta_id": "Q_31", "nombre_categoria": "Salud" },
    { "idx": 73, "id": 82, "pregunta_id": "Q_32", "nombre_categoria": "Educación" },
    { "idx": 74, "id": 83, "pregunta_id": "Q_33", "nombre_categoria": "Cultura y Recreación" },
    { "idx": 75, "id": 84, "pregunta_id": "Q_34_O1", "nombre_categoria": "Cultura y Recreación" },
    { "idx": 76, "id": 85, "pregunta_id": "Q_34_O2", "nombre_categoria": "Cultura y Recreación" },
    { "idx": 77, "id": 86, "pregunta_id": "Q_34_O3", "nombre_categoria": "Cultura y Recreación" },
    { "idx": 78, "id": 87, "pregunta_id": "Q_34_O4", "nombre_categoria": "Cultura y Recreación" },
    { "idx": 79, "id": 88, "pregunta_id": "Q_34_O5", "nombre_categoria": "Cultura y Recreación" },
    { "idx": 80, "id": 89, "pregunta_id": "Q_34_O6", "nombre_categoria": "Cultura y Recreación" },
    { "idx": 81, "id": 90, "pregunta_id": "Q_34_O7", "nombre_categoria": "Cultura y Recreación" },
    { "idx": 82, "id": 91, "pregunta_id": "Q_34_O8", "nombre_categoria": "Cultura y Recreación" },
    { "idx": 83, "id": 92, "pregunta_id": "Q_34_O9", "nombre_categoria": "Cultura y Recreación" },
    { "idx": 84, "id": 93, "pregunta_id": "Q_34_O10", "nombre_categoria": "Cultura y Recreación" },
    { "idx": 85, "id": 94, "pregunta_id": "Q_34_O11", "nombre_categoria": "Cultura y Recreación" },
    { "idx": 86, "id": 95, "pregunta_id": "Q_34_O12", "nombre_categoria": "Cultura y Recreación" },
    { "idx": 87, "id": 96, "pregunta_id": "Q_34_O13", "nombre_categoria": "Cultura y Recreación" },
    { "idx": 88, "id": 97, "pregunta_id": "Q_35", "nombre_categoria": "Vivienda" },
    { "idx": 89, "id": 98, "pregunta_id": "T_Q_36_1", "nombre_categoria": "Espacio público, desarrollo urbano, servicios públicos" },
    { "idx": 90, "id": 99, "pregunta_id": "T_Q_36_2", "nombre_categoria": "Espacio público, desarrollo urbano, servicios públicos" },
    { "idx": 91, "id": 100, "pregunta_id": "T_Q_36_3", "nombre_categoria": "Espacio público, desarrollo urbano, servicios públicos" },
    { "idx": 92, "id": 101, "pregunta_id": "T_Q_36_4", "nombre_categoria": "Espacio público, desarrollo urbano, servicios públicos" },
    { "idx": 93, "id": 102, "pregunta_id": "T_Q_36_5", "nombre_categoria": "Espacio público, desarrollo urbano, servicios públicos" },
    { "idx": 94, "id": 103, "pregunta_id": "T_Q_36_6", "nombre_categoria": "Espacio público, desarrollo urbano, servicios públicos" },
    { "idx": 95, "id": 104, "pregunta_id": "T_Q_37_1", "nombre_categoria": "Espacio público, desarrollo urbano, servicios públicos" },
    { "idx": 96, "id": 105, "pregunta_id": "T_Q_37_2", "nombre_categoria": "Espacio público, desarrollo urbano, servicios públicos" },
    { "idx": 97, "id": 106, "pregunta_id": "T_Q_37_3", "nombre_categoria": "Espacio público, desarrollo urbano, servicios públicos" },
    { "idx": 98, "id": 107, "pregunta_id": "T_Q_37_4", "nombre_categoria": "Espacio público, desarrollo urbano, servicios públicos" },
    { "idx": 99, "id": 108, "pregunta_id": "T_Q_37_5", "nombre_categoria": "Espacio público, desarrollo urbano, servicios públicos" }
]
